let stockProductos = [
    {id: 1, cantidad: 1, nombre: "Contabilidad Superior", tipo: "Libro", desc: "Ingresos en general", precio:  4300,autor: "Enrique Fowler Newton", stock: 15 ,img: "../img_stock/1.png" },
    {id: 2, cantidad: 1, nombre: "Contabilidad básica", tipo: "Libro", desc: "Contabilidad basica", precio: 3000, autor: "Enrique Fowler Newton", stock: 23, img: "../img_stock/2.jpg" },
    {id: 3, cantidad: 1, nombre: "Contabilidad y finanzas para Dummies", tipo: "Libro", desc: "Introducción a esta disciplina", precio: 4000, autor: "Oriol Amat", stock: 0, img: "../img_stock/3.jpg" },
    {id: 4, cantidad: 1, nombre: "Excel contable", tipo: "Libro", desc: "Excel", precio: 2500, autor: "César Oceda Samaniego", stock: 15, img: "../img_stock/4.jpg" },
    {id: 5, cantidad: 1, nombre: "Introducción a la contabilidad y las finanzas NE", tipo: "Libro", desc: "Introducción a contabilidad", precio: 4000, autor: "Oriol Amat", stock: 4, img: "../img_stock/5.jpg" },
    {id: 6, cantidad: 1, nombre: "Contabilidad y gestión de costes", tipo: "Libro", desc: "La contabilidad de costes", precio: 5000, autor: "Oriol Amat y Pilar Soldevila García", stock: 15, img: "../img_stock/6.jpg" },
    {id: 7, cantidad: 1, nombre: "Finanzas para emprendedores", tipo: "Libro", desc: "Finanzas", precio: 3500, autor: "Antonio Manzanera", stock: 15, img: "../img_stock/7.jpg" },
    {id: 8, cantidad: 1, nombre: "Manual Básico de Contabilidad: El Arte de la lógica Contable", tipo: "Libro", desc: "Introducción a contabilidad", precio: 4000, autor: "VEGA", stock: 15, img: "../img_stock/8.jpg" },
    {id: 9, cantidad: 1, nombre: "Contabilidad para numerofóbicos", tipo: "Libro", desc: " guía de supervivencia para propietarios", precio: 3780, autor: "Dawn Fotopulos", stock: 15, img: "../img_stock/9.jpg" },
    {id: 10, cantidad: 1, nombre: "La ciencia del bienestar", tipo: "Libro", desc: "Los 5 elementos esenciales", precio: 7000, autor: "Tom Rath", stock: 0, img: "../img_stock/10.jpg" },
]

let bancos = [
     {banco : "https://criptoya.com/api/bbva"},
    {banco : "https://criptoya.com/api/ciudad"},
    {banco : "https://criptoya.com/api/galicia"},
    {banco : "https://criptoya.com/api/hsbc"},
    {banco : "https://criptoya.com/api/macro"},
    {banco : "https://criptoya.com/api/bna"},
    {banco : "https://criptoya.com/api/patagonia"},
    {banco : "https://criptoya.com/api/bapro"},
    {banco : "https://criptoya.com/api/santander"},
    {banco : "https://criptoya.com/api/supervielle"},
    {banco : "https://criptoya.com/api/brubank"},
    {banco : "https://criptoya.com/api/buendolar"},
    {banco : "https://criptoya.com/api/cambioposadas"},
    {banco : "https://criptoya.com/api/cambiosroca"},
    {banco : "https://criptoya.com/api/davsa"},
    {banco : "https://criptoya.com/api/dolariol"},
    {banco : "https://criptoya.com/api/naranjax"},
    {banco : "https://criptoya.com/api/plus"},
    {banco : "https://criptoya.com/api/prex"},
    {banco : "https://criptoya.com/api/rebanking"},
    {banco : "https://criptoya.com/api/tiendadolar"},
]